Repository vzetaa/zeta, pull requests merged in 2021-12, with the labels that each got.

#22 feat: rename repo to kogasa
  README.md
  SlashCommands/Info/help.js
  commands/Info/help.js
  commands/Learn/random-hiragana.js
  commands/Learn/random-katakana.js
  docs/README.md
  docs/_config.yml
  docs/p/getting-started.md
  package.json
Labels: enhancement

#33 feat: completing docs
  docs/README.md
  docs/p/commands/README.md
  docs/p/commands/admin.md
  docs/p/commands/database.md
  docs/p/commands/documents.md
  docs/p/commands/images.md
  docs/p/commands/info.md
  docs/p/commands/reddit.md
  docs/p/commands/utility.md
  docs/p/getting-started.md
  docs/p/inviting.md
Labels: enhancement

#47 [Patch 1] Rename Repository Name
  README.md
  docs/README.md
  docs/_config.yml
  docs/_layouts/default.html
  docs/changelog.md
  docs/rename-schedule.md
  package.json
  src/Commands/Info/Botinfo.ts
  src/Commands/Info/Help.ts
  src/Commands/Info/Ping.ts
  src/Commands/Info/Uptime.ts
  src/Slash/Info/Botinfo.ts
  src/Slash/Info/Help.ts
  src/Slash/Info/Ping.ts
  src/Slash/Info/Uptime.ts
Labels: enhancement

#54 [Feature] Vtubers category
  .env.example
  docs/README.md
  docs/p/commands/README.md
  docs/p/commands/vtubers.md
  package.json
  src/Commands/VTubers/Channel-Info.ts
  src/Commands/VTubers/Upcoming-stream.ts
  src/Commands/VTubers/Video-metadata.ts
  src/Exports/Holodex.ts
  src/Interfaces/Config.ts
  yarn.lock
Labels: 📄 Documentation, ➕ Enhancement, 🈸 Feature Request

#65 feat: add some configuration for kodiak
  .github/.kodiak.toml
Labels: 🚀 Ready to merge, 🤖 Auto merge

#66 chore: set merge method to default merge
  .github/.kodiak.toml
Labels: 🚀 Ready to merge, 🤖 Auto merge

#67 docs: update announcements
  docs/README.md
Labels: 🚀 Ready to merge, 🤖 Auto merge

#68 chore: remove husky & lint-staged configuration
  package.json
Labels: ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge, chore

#69 chore: remove commitlint deps & configuration
  package.json
  yarn.lock
Labels: ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge, chore

#70 docs: docs update
  docs/changelog.md
  docs/p/getting-started.md
Labels: 📄 Documentation, ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge

#71 docs: fix typo & layouts update
  docs/_layouts/default.html
  docs/changelog.md
Labels: 📄 Documentation, ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge

#72 chore: remove tslint
  tslint.json
Labels: ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge, chore

#73 chore: remove binary files & docs update
  .github/workflows/Build.yml
  docs/README.md
  docs/p/getting-started.md
  package.json
  src/Bin/Build.ts
  src/Bin/CI.ts
Labels: 📄 Documentation, ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge, chore

#74 docs: update footer layouts
  docs/_layouts/default.html
Labels: 📄 Documentation, ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge

#75 docs: remove extra dots
  docs/README.md
  docs/_layouts/default.html
Labels: 📄 Documentation, ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge

#76 chore: update presence text
  src/Events/Ready.ts
Labels: ✅ CI Passing, 🚀 Ready to merge, chore

#80 chore: remove strip_html_comments option
  .github/.kodiak.toml
Labels: ✅ CI Passing, 🚀 Ready to merge, 🤖 Auto merge, chore
